### ISSUE TITLE
Login/Signup Page

### ISSUE THREAD

**Issue by lawrencenlee** [CS130-W20/team-B8#1]
## User Story
As a user, I would like to login and signup to the app so that I can create and find events.

## Detailed Description
The login and signup page should let users create accounts that get stored in a database. Users should be able to login and signup with an email, username, and password.

## Acceptance Criteria
- [x] Design the Login and Signup page
- [x] Given user is logged out, then log-in page allows them to sign-up or login
- [x] Given user attempts to login without an existing account, prompt user to signup

**Comment by dermanyang** [comment]
Login page was designed and built. Accounts are saved successfully and users can login. Needs to be integrated with app and mongo database.

**Comment by dermanyang** [comment]
Login page designed, created, integrated with app an ddatabase.
