### ISSUE TITLE
User Database Management

### ISSUE THREAD

**Issue by Phipson** [CS130-W20/team-B8#3]
## User Story
As a Back-end Developer, I would like to store and partition user so that users can securely and reliably access their own data.

## Detailed Description
User account data should be stored such that it can be reliably accessed and updated according to user location. 

## Acceptance Criteria
- [x] Given a new user, then database should generate a new entry
- [x] Given an existing user, then database should check that information is valid
- [x] Given user's GPS location, then database should update and store the user's location
- [x] Given a user attending an event, then database should add event to user account info.

**Comment by dermanyang** [comment]
CRUD functionalities work with mongoDB. Database calls written in node.js wrapped with socket.io event calls to interact with front-end. Still need to implement authentication properly.
